# Generated by Django 5.1.4 on 2025-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='path/to/default/cover.jpg', null=True, upload_to='users/cover_pictures'),
        ),
    ]
